AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
    EnvName:
        Description: "Your environment name here"
        Type: String
        Default: defalt

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'tom1-test-deploy-bucket-${EnvName}'